import { Poppins_400Regular } from "@expo-google-fonts/poppins";
import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    width: "100%",
    backgroundColor: "#cbf3f5",
  },
  inputContainer: {
    backgroundColor: "white",
    justifyContent: "center",
    width: "80%",
    height: "70%",
    padding: 20,
    borderRadius: 10,
    shadowRadius: 20,
    shadowColor: "black",
    shadowOpacity: 0.8,
    shadowOffset: {
      height: 6,
      width: 6,
    },
    elevation: 10,
    gap: 20,
    zIndex: 0,
    marginTop: 50,
  },
  textInput: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    height: 40,
    borderColor: "#D3D3D3",
    borderWidth: 1,
    borderRadius: 5,
    paddingLeft: 8,
  },
  inputBox: {
    height: "100%",
  },
  inputField: {
    gap: 1,
  },
  textStyle: {
    fontSize: 10,
    fontFamily: "Poppins-SemiBold",
  },
  dropDowns: {
    width: "56%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropDown: {
    width: 120,
    borderRadius: 10,
    borderColor: "grey",
    color: "grey",
  },
  card: {
    height: 180,
    width: 280,
    borderRadius: 20,
  },
  imageContainer: {
    height: 180,
    width: 280,
    borderRadius: 20,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
      },
      android: {
        elevation: 10,
      },
    }),
    top: 30,
    zIndex: 1,
    position: "absolute",
  },
  forOverlay: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 30,
  },
  cardIconContainer: {
    marginTop: 0,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: 20,
    paddingRight: 20,
  },
  cardNumbersContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 15,
    paddingRight: 20,
    zIndex: 2,
    marginBottom: 16,
  },
  cardDatesContainer: {
    marginTop: 0,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: 15,
    paddingRight: 20,
    zIndex: 2,
  },
  hej: {
    color: "blue",
  },
  cardContainer: {
    height: 180,
    width: 280,
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    alignItems: "center",
    zIndex: 2,
    alignSelf: "flex-end",
  },
  chip: {
    height: 50,
    width: 50,
  },
  topRowCard: {
    marginTop: 0,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  company: {
    height: 70,
    width: 70,
    alignSelf: "flex-end",
  },
  numbers: {
    color: "white",
    zIndex: 3,
    fontFamily: "Poppins-SemiBold",
  },
  numberBorder: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 5,
    width: "100%",
    padding: 9,
  },
  numberBorderCvv: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 5,
    width: "100%",
    padding: 9,
  },
  cardHolder: {
    color: "white",
    zIndex: 3,
    textTransform: "uppercase",
    fontSize: 12,
  },
  holderTitle: {
    color: "gray",
    zIndex: 3,
    fontSize: 8,
  },
  cardHolderContainer: {
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderColor: "white",
    zIndex: 3,
    padding: 5,
    width: "70%",
    borderRadius: 5,
  },
  dates: {
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderColor: "white",
    zIndex: 3,
    padding: 5,
    width: "30%",
    borderRadius: 5,
  },
  blackBar: {
    backgroundColor: "black",
    marginTop: 20,
    height: 35,
    width: "99.5%",
  },
  cvvContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 5,
    marginBottom: 0,
    width: "100%",
    zIndex: 3,
    paddingRight: 20,
  },
  cvvText: {
    color: "white",
    zIndex: 3,
    fontSize: 13,
    fontFamily: "Poppins-SemiBold",
  },
});

export default styles;
